"use strict";

function seedState() {
  const now = new Date();
  const month = now.getMonth() + 1;
  const year = now.getFullYear();
  const key = makePeriodKey(month, year);
  const d = (day) => `${year}-${pad(month)}-${pad(day)}`;
  const employees = [
    {
      id: id(),
      fullName: "Nadia Benali",
      function: "Accountant",
      birthDate: "1991-04-12",
      birthPlace: "Oran",
      address: "ModernLam site",
      phone01: "0550000001",
      phone02: "",
      socialSecurityNumber: "CNAS-001",
      anemNumber: "ANEM-001",
      status: "Active",
    },
    {
      id: id(),
      fullName: "Karim Haddad",
      function: "Cash Desk",
      birthDate: "1988-09-22",
      birthPlace: "Tlemcen",
      address: "ModernLam site",
      phone01: "0550000002",
      phone02: "",
      socialSecurityNumber: "CNAS-002",
      anemNumber: "ANEM-002",
      status: "Active",
    },
    {
      id: id(),
      fullName: "Samira Mansouri",
      function: "HR",
      birthDate: "1994-01-18",
      birthPlace: "Sidi Bel Abbes",
      address: "ModernLam site",
      phone01: "0550000003",
      phone02: "",
      socialSecurityNumber: "CNAS-003",
      anemNumber: "ANEM-003",
      status: "Active",
    },
  ];
  const suppliers = [
    {
      id: id(),
      name: "BioPlus Reagents",
      category: "Reagents & Consumables",
      phone: "041000001",
      address: "Oran",
      notes: "Primary reagent supplier",
      isActive: true,
    },
    {
      id: id(),
      name: "OfficeLine",
      category: "IT & Office",
      phone: "041000002",
      address: "Alger",
      notes: "",
      isActive: true,
    },
  ];
  const supplierTransactionId = id();
  return {
    selected: { month, year },
    periods: [
      {
        id: id(),
        month,
        year,
        status: "Open",
        openedAt: now.toISOString(),
        openedBy: "Admin",
        closedAt: "",
        closedBy: "",
        closeNote: "",
      },
    ],
    employees,
    suppliers,
    cashExpenses: [
      {
        id: id(),
        periodKey: key,
        date: d(2),
        designation: "Small cash supplies",
        amount: 4200,
        remark: "Validated by accounting",
        attachmentRef: "receipt-001",
        status: "Validated",
        createdAt: now.toISOString(),
      },
    ],
    cashClosures: [
      {
        id: id(),
        periodKey: key,
        date: d(2),
        user: "Karim Haddad",
        realAmount: 128500,
        virtualAmount: 128500,
        difference: 0,
        remark: "",
        status: "Validated",
        createdAt: now.toISOString(),
      },
      {
        id: id(),
        periodKey: key,
        date: d(3),
        user: "Karim Haddad",
        realAmount: 141200,
        virtualAmount: 140900,
        difference: 300,
        remark: "Late manual receipt",
        status: "Validated",
        createdAt: now.toISOString(),
      },
    ],
    cashMovements: [
      {
        id: id(),
        periodKey: key,
        date: d(2),
        cashCv: 78000,
        cashC: 50500,
        tpe: 18700,
        expenses: 4200,
        reimbursement: 0,
        convention: 12500,
        subcontractors: 8300,
        total: 173200,
        remark: "",
        status: "Validated",
        createdAt: now.toISOString(),
      },
    ],
    additionalEntries: [
      {
        id: id(),
        periodKey: key,
        date: d(4),
        amount: 18000,
        detail: "Manual correction entry",
        paymentStatus: "Paid",
        remark: "",
        status: "Validated",
        createdAt: now.toISOString(),
      },
    ],
    safeExits: [
      {
        id: id(),
        periodKey: key,
        date: d(5),
        designation: "Rent payment",
        amount: 45000,
        category: "Rent",
        attachmentRef: "rent-note",
        remark: "",
        status: "Validated",
        createdAt: now.toISOString(),
      },
    ],
    profitabilityMovements: [
      {
        id: id(),
        periodKey: key,
        date: d(6),
        amount: 15000,
        detail: "Previous month carry-over",
        movementType: "Entry",
        sourcePeriod: "",
        destinationPeriod: key,
        status: "Validated",
        createdAt: now.toISOString(),
      },
    ],
    supplierTransactions: [
      {
        id: supplierTransactionId,
        periodKey: key,
        supplierId: suppliers[0].id,
        category: "Reagents & Consumables",
        date: d(6),
        orderTotal: 96000,
        paidAmount: 40000,
        remainingAmount: 56000,
        paymentMode: "Cheque",
        reference: "CH-102",
        status: "Partial",
        observation: "Partial payment",
        createdAt: now.toISOString(),
      },
    ],
    payments: [
      {
        id: id(),
        periodKey: key,
        targetType: "supplier",
        targetId: supplierTransactionId,
        date: d(6),
        amount: 40000,
        paymentMode: "Cheque",
        reference: "CH-102",
        note: "",
        status: "Validated",
        createdAt: now.toISOString(),
      },
    ],
    partners: [
      {
        id: id(),
        periodKey: key,
        type: "Subcontractor",
        name: "External Lab A",
        amount: 32000,
        payment: 32000,
        receptionDate: d(7),
        paymentMode: "Transfer",
        remainingBalance: 0,
        status: "Paid",
        remarks: "",
        createdAt: now.toISOString(),
      },
      {
        id: id(),
        periodKey: key,
        type: "Convention",
        name: "Company Convention B",
        amount: 54000,
        payment: 25000,
        receptionDate: d(8),
        paymentMode: "Cheque",
        remainingBalance: 29000,
        status: "Partial",
        remarks: "",
        createdAt: now.toISOString(),
      },
    ],
    attendance: [
      {
        id: id(),
        periodKey: key,
        employeeId: employees[0].id,
        date: d(1),
        dayCode: "P",
        note: "",
        status: "Validated",
        createdAt: now.toISOString(),
      },
      {
        id: id(),
        periodKey: key,
        employeeId: employees[1].id,
        date: d(1),
        dayCode: "G",
        note: "Night guard",
        status: "Validated",
        createdAt: now.toISOString(),
      },
    ],
    salaryReports: [
      {
        id: id(),
        periodKey: key,
        employeeId: employees[0].id,
        baseNetSalary: 70000,
        overtimePresence: 0,
        lamTravel: 4000,
        nightGuard: 0,
        fridayDayGuard: 0,
        fridayNightGuard: 0,
        absence: 0,
        bonus: 5000,
        leave: 0,
        penalties: 0,
        advances: 0,
        finalSalary: 79000,
        status: "Draft",
        remark: "",
        createdAt: now.toISOString(),
      },
    ],
    contracts: employees.map((employee) => ({
      id: id(),
      employeeId: employee.id,
      hireDate: "2023-01-01",
      cnasRegistrationDate: "2023-01-10",
      contractType: "CDI",
      startsAt: "2023-01-01",
      endsAt: "",
      resignationDate: "",
      status: "Active",
      remark: "",
      createdAt: now.toISOString(),
    })),
    leaves: employees.map((employee) => ({
      id: id(),
      employeeId: employee.id,
      year,
      acquiredDays: 30,
      usedDays: 4,
      remainingDays: 26,
      remark: "",
      createdAt: now.toISOString(),
    })),
    vehicleExpenses: [
      {
        id: id(),
        periodKey: key,
        date: d(9),
        amount: 6200,
        details: "Fuel",
        mileage: 75000,
        gplExtraKm: 0,
        essenceExtraKm: 120,
        status: "Validated",
        createdAt: now.toISOString(),
      },
    ],
    cheques: [
      {
        id: id(),
        periodKey: key,
        date: d(10),
        beneficiary: "BioPlus Reagents",
        chequeNumber: "CH-102",
        amount: 40000,
        entries: 0,
        exits: 40000,
        designation: "Supplier payment",
        month: monthNames[month - 1],
        status: "Validated",
        createdAt: now.toISOString(),
      },
    ],
    encashments: [
      {
        id: id(),
        periodKey: key,
        date: d(2),
        designation: "DIVERS CLIENTS",
        observations: "",
        amount: 128500,
        status: "Validated",
        createdAt: now.toISOString(),
      },
    ],
    users: [
      {
        id: id(),
        username: "admin",
        fullName: "Administrator",
        role: "Admin",
        isActive: true,
        lastLoginAt: now.toISOString(),
      },
    ],
    auditLogs: [
      {
        id: id(),
        user: "Admin",
        action: "Seed prototype data",
        entityType: "prototype",
        entityId: "initial",
        oldValues: "",
        newValues: "Initial browser data",
        reason: "Prototype setup",
        createdAt: now.toISOString(),
      },
    ],
    reportExports: [],
  };
}
