"use strict";

function seedState() {
  const now = new Date();
  const month = now.getMonth() + 1;
  const year = now.getFullYear();
  const periodContext = (offset) => {
    const date = new Date(year, month - 1 + offset, 1);
    const contextMonth = date.getMonth() + 1;
    const contextYear = date.getFullYear();
    return {
      month: contextMonth,
      year: contextYear,
      key: makePeriodKey(contextMonth, contextYear),
      d: (day) => `${contextYear}-${pad(contextMonth)}-${pad(day)}`,
      monthName: monthNames[contextMonth - 1],
    };
  };
  const open = periodContext(0);
  const review = periodContext(-1);
  const closed = periodContext(-2);
  const nowIso = now.toISOString();

  const employees = [
    {
      id: id(),
      fullName: "Nadia Benali",
      function: "Accountant",
      birthDate: "1991-04-12",
      birthPlace: "Oran",
      address: "ModernLam site",
      phone01: "0550000001",
      phone02: "",
      socialSecurityNumber: "CNAS-001",
      anemNumber: "ANEM-001",
      status: "Active",
    },
    {
      id: id(),
      fullName: "Karim Haddad",
      function: "Cash Desk",
      birthDate: "1988-09-22",
      birthPlace: "Tlemcen",
      address: "ModernLam site",
      phone01: "0550000002",
      phone02: "",
      socialSecurityNumber: "CNAS-002",
      anemNumber: "ANEM-002",
      status: "Active",
    },
    {
      id: id(),
      fullName: "Samira Mansouri",
      function: "HR",
      birthDate: "1994-01-18",
      birthPlace: "Sidi Bel Abbes",
      address: "ModernLam site",
      phone01: "0550000003",
      phone02: "",
      socialSecurityNumber: "CNAS-003",
      anemNumber: "ANEM-003",
      status: "Active",
    },
    {
      id: id(),
      fullName: "Yacine Merabet",
      function: "Lab Assistant",
      birthDate: "1997-07-03",
      birthPlace: "Oran",
      address: "ModernLam site",
      phone01: "0550000004",
      phone02: "",
      socialSecurityNumber: "CNAS-004",
      anemNumber: "ANEM-004",
      status: "Active",
    },
  ];

  const suppliers = [
    {
      id: id(),
      name: "BioPlus Reagents",
      category: "Reagents & Consumables",
      phone: "041000001",
      address: "Oran",
      notes: "Primary reagent supplier",
      isActive: true,
    },
    {
      id: id(),
      name: "OfficeLine",
      category: "IT & Office",
      phone: "041000002",
      address: "Alger",
      notes: "Office and printer supplies",
      isActive: true,
    },
    {
      id: id(),
      name: "MedEquip Maintenance",
      category: "Investment",
      phone: "041000003",
      address: "Tlemcen",
      notes: "Equipment maintenance and spare parts",
      isActive: true,
    },
  ];

  const paidSupplierTransactionId = id();
  const partialSupplierTransactionId = id();
  const unpaidSupplierTransactionId = id();
  const reviewSupplierTransactionId = id();
  const subcontractorPartnerId = id();
  const conventionPartnerId = id();
  const closedPartnerId = id();

  return {
    selected: { month: open.month, year: open.year },
    settings: { ...defaultPrototypeSettings },
    periods: [
      {
        id: id(),
        month: open.month,
        year: open.year,
        status: "Open",
        openedAt: nowIso,
        openedBy: defaultPrototypeSettings.currentUserDisplayName,
        closedAt: "",
        closedBy: "",
        closeNote: "",
      },
      {
        id: id(),
        month: review.month,
        year: review.year,
        status: "Under review",
        openedAt: nowIso,
        openedBy: defaultPrototypeSettings.currentUserDisplayName,
        closedAt: "",
        closedBy: "",
        closeNote: "Prototype under-review month with remaining balances.",
      },
      {
        id: id(),
        month: closed.month,
        year: closed.year,
        status: "Closed",
        openedAt: nowIso,
        openedBy: defaultPrototypeSettings.currentUserDisplayName,
        closedAt: nowIso,
        closedBy: defaultPrototypeSettings.currentUserDisplayName,
        closeNote: "Closed seed scenario with official export trace.",
      },
    ],
    employees,
    suppliers,
    cashExpenses: [
      {
        id: id(),
        periodKey: open.key,
        date: open.d(2),
        designation: "Small cash supplies",
        amount: 4200,
        remark: "Validated by accounting",
        attachmentRef: "receipt-001",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: review.key,
        date: review.d(3),
        designation: "Courier and small office expenses",
        amount: 3500,
        remark: "Under review with accounting",
        attachmentRef: "receipt-review-001",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: closed.key,
        date: closed.d(4),
        designation: "Closed month petty cash",
        amount: 2800,
        remark: "Closed period expense",
        attachmentRef: "receipt-closed-001",
        status: "Validated",
        createdAt: nowIso,
      },
    ],
    cashClosures: [
      {
        id: id(),
        periodKey: open.key,
        date: open.d(2),
        user: "Karim Haddad",
        realAmount: 128500,
        virtualAmount: 128500,
        difference: 0,
        remark: "",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: open.key,
        date: open.d(3),
        user: "Karim Haddad",
        realAmount: 141200,
        virtualAmount: 140900,
        difference: 300,
        remark: "Late manual receipt",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: open.key,
        date: open.d(4),
        user: "Nadia Benali",
        realAmount: 99600,
        virtualAmount: 100000,
        difference: -400,
        remark: "",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: review.key,
        date: review.d(5),
        user: "Karim Haddad",
        realAmount: 110600,
        virtualAmount: 110000,
        difference: 600,
        remark: "Pending manager review",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: closed.key,
        date: closed.d(6),
        user: "Karim Haddad",
        realAmount: 132000,
        virtualAmount: 132000,
        difference: 0,
        remark: "",
        status: "Validated",
        createdAt: nowIso,
      },
    ],
    cashMovements: [
      {
        id: id(),
        periodKey: open.key,
        date: open.d(2),
        cashCv: 78000,
        cashC: 50500,
        tpe: 18700,
        expenses: 4200,
        reimbursement: 0,
        convention: 12500,
        subcontractors: 8300,
        total: 173200,
        remark: "",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: open.key,
        date: open.d(3),
        cashCv: 84500,
        cashC: 56700,
        tpe: 22400,
        expenses: 3100,
        reimbursement: 0,
        convention: 17400,
        subcontractors: 9100,
        total: 193200,
        remark: "Busy weekday",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: review.key,
        date: review.d(2),
        cashCv: 72000,
        cashC: 42000,
        tpe: 18000,
        expenses: 3500,
        reimbursement: 0,
        convention: 10200,
        subcontractors: 7600,
        total: 153300,
        remark: "Under-review movement",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: closed.key,
        date: closed.d(2),
        cashCv: 91000,
        cashC: 61200,
        tpe: 24500,
        expenses: 2800,
        reimbursement: 0,
        convention: 18400,
        subcontractors: 11100,
        total: 209000,
        remark: "Closed period movement",
        status: "Validated",
        createdAt: nowIso,
      },
    ],
    additionalEntries: [
      {
        id: id(),
        periodKey: open.key,
        date: open.d(4),
        amount: 18000,
        detail: "Manual correction entry",
        paymentStatus: "Paid",
        remark: "",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: closed.key,
        date: closed.d(5),
        amount: 12000,
        detail: "Closed month adjustment",
        paymentStatus: "Paid",
        remark: "",
        status: "Validated",
        createdAt: nowIso,
      },
    ],
    safeExits: [
      {
        id: id(),
        periodKey: open.key,
        date: open.d(5),
        designation: "Rent payment",
        amount: 45000,
        category: "Rent",
        attachmentRef: "rent-note",
        remark: "",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: closed.key,
        date: closed.d(8),
        designation: "Closed month tax payment",
        amount: 22000,
        category: "Taxes",
        attachmentRef: "tax-note",
        remark: "",
        status: "Validated",
        createdAt: nowIso,
      },
    ],
    profitabilityMovements: [
      {
        id: id(),
        periodKey: open.key,
        date: open.d(6),
        amount: 15000,
        detail: "Previous month carry-over",
        movementType: "Entry",
        sourcePeriod: closed.key,
        destinationPeriod: open.key,
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: closed.key,
        date: closed.d(10),
        amount: 8000,
        detail: "Closed month reserve transfer",
        movementType: "Exit",
        sourcePeriod: closed.key,
        destinationPeriod: review.key,
        status: "Validated",
        createdAt: nowIso,
      },
    ],
    supplierTransactions: [
      {
        id: paidSupplierTransactionId,
        periodKey: open.key,
        supplierId: suppliers[1].id,
        category: "IT & Office",
        date: open.d(5),
        orderTotal: 18500,
        paidAmount: 18500,
        remainingAmount: 0,
        paymentMode: "Transfer",
        reference: "TR-201",
        status: "Paid",
        observation: "Paid office supplies",
        createdAt: nowIso,
      },
      {
        id: partialSupplierTransactionId,
        periodKey: open.key,
        supplierId: suppliers[0].id,
        category: "Reagents & Consumables",
        date: open.d(6),
        orderTotal: 96000,
        paidAmount: 40000,
        remainingAmount: 56000,
        paymentMode: "Cheque",
        reference: "CH-102",
        status: "Partial",
        observation: "Partial payment",
        createdAt: nowIso,
      },
      {
        id: unpaidSupplierTransactionId,
        periodKey: open.key,
        supplierId: suppliers[2].id,
        category: "Investment",
        date: open.d(9),
        orderTotal: 125000,
        paidAmount: 0,
        remainingAmount: 125000,
        paymentMode: "",
        reference: "INV-220",
        status: "Unpaid",
        observation: "Awaiting validation before payment",
        createdAt: nowIso,
      },
      {
        id: reviewSupplierTransactionId,
        periodKey: review.key,
        supplierId: suppliers[0].id,
        category: "Reagents & Consumables",
        date: review.d(11),
        orderTotal: 54000,
        paidAmount: 24000,
        remainingAmount: 30000,
        paymentMode: "Cheque",
        reference: "CH-099",
        status: "Partial",
        observation: "Under-review supplier balance",
        createdAt: nowIso,
      },
    ],
    payments: [
      {
        id: id(),
        periodKey: open.key,
        targetType: "supplier",
        targetId: paidSupplierTransactionId,
        date: open.d(5),
        amount: 18500,
        paymentMode: "Transfer",
        reference: "TR-201",
        note: "Full supplier payment",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: open.key,
        targetType: "supplier",
        targetId: partialSupplierTransactionId,
        date: open.d(6),
        amount: 40000,
        paymentMode: "Cheque",
        reference: "CH-102",
        note: "Partial supplier payment",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: review.key,
        targetType: "supplier",
        targetId: reviewSupplierTransactionId,
        date: review.d(11),
        amount: 24000,
        paymentMode: "Cheque",
        reference: "CH-099",
        note: "Under-review supplier payment",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: open.key,
        targetType: "partner",
        targetId: subcontractorPartnerId,
        date: open.d(7),
        amount: 32000,
        paymentMode: "Transfer",
        reference: "SUB-001",
        note: "Subcontractor fully paid",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: open.key,
        targetType: "partner",
        targetId: conventionPartnerId,
        date: open.d(8),
        amount: 25000,
        paymentMode: "Cheque",
        reference: "CONV-001",
        note: "Convention partial payment",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: closed.key,
        targetType: "partner",
        targetId: closedPartnerId,
        date: closed.d(9),
        amount: 41000,
        paymentMode: "Transfer",
        reference: "SUB-CLOSED",
        note: "Closed month partner payment",
        status: "Validated",
        createdAt: nowIso,
      },
    ],
    partners: [
      {
        id: subcontractorPartnerId,
        periodKey: open.key,
        type: "Subcontractor",
        name: "External Lab A",
        amount: 32000,
        payment: 32000,
        receptionDate: open.d(7),
        paymentMode: "Transfer",
        remainingBalance: 0,
        status: "Paid",
        remarks: "Subcontractor paid",
        createdAt: nowIso,
      },
      {
        id: conventionPartnerId,
        periodKey: open.key,
        type: "Convention",
        name: "Company Convention B",
        amount: 54000,
        payment: 25000,
        receptionDate: open.d(8),
        paymentMode: "Cheque",
        remainingBalance: 29000,
        status: "Partial",
        remarks: "Convention partial payment",
        createdAt: nowIso,
      },
      {
        id: closedPartnerId,
        periodKey: closed.key,
        type: "Subcontractor",
        name: "External Lab Closed",
        amount: 41000,
        payment: 41000,
        receptionDate: closed.d(9),
        paymentMode: "Transfer",
        remainingBalance: 0,
        status: "Paid",
        remarks: "Closed month subcontractor",
        createdAt: nowIso,
      },
    ],
    attendance: [
      {
        id: id(),
        periodKey: open.key,
        employeeId: employees[0].id,
        date: open.d(1),
        dayCode: "P",
        note: "",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: open.key,
        employeeId: employees[1].id,
        date: open.d(1),
        dayCode: "G",
        note: "Night guard",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: open.key,
        employeeId: employees[2].id,
        date: open.d(2),
        dayCode: "P+",
        note: "Extra presence",
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: closed.key,
        employeeId: employees[0].id,
        date: closed.d(2),
        dayCode: "P",
        note: "Closed month attendance",
        status: "Validated",
        createdAt: nowIso,
      },
    ],
    salaryReports: [
      {
        id: id(),
        periodKey: open.key,
        employeeId: employees[0].id,
        baseNetSalary: 70000,
        overtimePresence: 0,
        lamTravel: 4000,
        nightGuard: 0,
        fridayDayGuard: 0,
        fridayNightGuard: 0,
        absence: 0,
        bonus: 5000,
        leave: 0,
        penalties: 0,
        advances: 0,
        finalSalary: 79000,
        status: "Draft",
        remark: "Draft salary scenario",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: open.key,
        employeeId: employees[1].id,
        baseNetSalary: 62000,
        overtimePresence: 2500,
        lamTravel: 3000,
        nightGuard: 4500,
        fridayDayGuard: 0,
        fridayNightGuard: 0,
        absence: 0,
        bonus: 0,
        leave: 0,
        penalties: 0,
        advances: 0,
        finalSalary: 72000,
        status: "Validated",
        remark: "Validated salary scenario",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: open.key,
        employeeId: employees[2].id,
        baseNetSalary: 66000,
        overtimePresence: 0,
        lamTravel: 3000,
        nightGuard: 0,
        fridayDayGuard: 0,
        fridayNightGuard: 0,
        absence: 0,
        bonus: 4000,
        leave: 0,
        penalties: 0,
        advances: 2000,
        finalSalary: 71000,
        status: "Paid",
        remark: "Paid salary scenario",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: closed.key,
        employeeId: employees[0].id,
        baseNetSalary: 70000,
        overtimePresence: 0,
        lamTravel: 4000,
        nightGuard: 0,
        fridayDayGuard: 0,
        fridayNightGuard: 0,
        absence: 0,
        bonus: 3000,
        leave: 0,
        penalties: 0,
        advances: 0,
        finalSalary: 77000,
        status: "Paid",
        remark: "Closed month salary",
        createdAt: nowIso,
      },
    ],
    contracts: [
      ...employees.slice(0, 3).map((employee) => ({
        id: id(),
        employeeId: employee.id,
        hireDate: "2023-01-01",
        cnasRegistrationDate: "2023-01-10",
        contractType: "CDI",
        startsAt: "2023-01-01",
        endsAt: "",
        resignationDate: "",
        status: "Active",
        remark: "",
        createdAt: nowIso,
      })),
      {
        id: id(),
        employeeId: employees[3].id,
        hireDate: "2024-01-15",
        cnasRegistrationDate: "2024-01-20",
        contractType: "CDD",
        startsAt: "2024-01-15",
        endsAt: `${open.year}-${pad(open.month)}-01`,
        resignationDate: "",
        status: "Expired",
        remark: "Employee without active contract scenario",
        createdAt: nowIso,
      },
    ],
    leaves: employees.slice(0, 3).map((employee) => ({
      id: id(),
      employeeId: employee.id,
      year: open.year,
      acquiredDays: 30,
      usedDays: 4,
      remainingDays: 26,
      remark: "",
      createdAt: nowIso,
    })),
    vehicleExpenses: [
      {
        id: id(),
        periodKey: open.key,
        date: open.d(9),
        amount: 6200,
        details: "Fuel",
        mileage: 75000,
        gplExtraKm: 0,
        essenceExtraKm: 120,
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: closed.key,
        date: closed.d(9),
        amount: 5800,
        details: "Closed month service vehicle fuel",
        mileage: 74880,
        gplExtraKm: 0,
        essenceExtraKm: 110,
        status: "Validated",
        createdAt: nowIso,
      },
    ],
    cheques: [
      {
        id: id(),
        periodKey: open.key,
        date: open.d(10),
        beneficiary: "BioPlus Reagents",
        chequeNumber: "CH-102",
        amount: 40000,
        entries: 0,
        exits: 40000,
        designation: "Supplier partial payment",
        month: open.monthName,
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: closed.key,
        date: closed.d(11),
        beneficiary: "External Lab Closed",
        chequeNumber: "CH-088",
        amount: 41000,
        entries: 0,
        exits: 41000,
        designation: "Closed subcontractor payment",
        month: closed.monthName,
        status: "Validated",
        createdAt: nowIso,
      },
    ],
    encashments: [
      {
        id: id(),
        periodKey: open.key,
        date: open.d(2),
        designation: "DIVERS CLIENTS",
        observations: "",
        amount: 128500,
        status: "Validated",
        createdAt: nowIso,
      },
      {
        id: id(),
        periodKey: closed.key,
        date: closed.d(3),
        designation: "DIVERS CLIENTS",
        observations: "Closed month encashment",
        amount: 132000,
        status: "Validated",
        createdAt: nowIso,
      },
    ],
    users: [
      {
        id: id(),
        username: "admin",
        fullName: "Administrator",
        role: "Admin",
        isActive: true,
        lastLoginAt: nowIso,
      },
    ],
    attachments: [],
    auditLogs: [
      {
        id: id(),
        user: defaultPrototypeSettings.currentUserDisplayName,
        action: "Seed prototype data",
        entityType: "prototype",
        entityId: "initial",
        oldValues: "",
        newValues: "Initial browser scenarios for open, under-review, and closed months",
        reason: "Prototype setup",
        createdAt: nowIso,
      },
    ],
    reportExports: [
      {
        id: id(),
        reportName: "Closed Month Balance",
        period: closed.key,
        format: "Official PDF print",
        generatedBy: defaultPrototypeSettings.currentUserDisplayName,
        generatedAt: nowIso,
      },
      {
        id: id(),
        reportName: "Under Review Supplier Journal",
        period: review.key,
        format: "CSV",
        generatedBy: defaultPrototypeSettings.currentUserDisplayName,
        generatedAt: nowIso,
      },
    ],
  };
}
