(() => {
  "use strict";
  const M = window.ModernLamPrototype;
  const {
    state,
    labInfo,
    monthNames,
    supplierCategories,
    paymentModes,
    partnerTypes,
    paymentStatuses,
    salaryStatuses,
    dayCodes,
    roles,
    renderHeader,
    closedNotice,
    renderMetrics,
    totals,
    money,
    renderSection,
    renderTable,
    scopedRows,
    renderForm,
    defaultDate,
    currentPeriodKey,
    supplierName,
    employeeName,
    paymentTargetLabel,
    employeeFunction,
    cashMovementStats,
    daysInMonth,
    pad,
    optionList,
    number,
    sum,
    statusPill,
    escapeHtml
  } = M;
  function renderReports() {
    const reportOptions = [
      ["cashExpenses", "Cash Expenses"],
      ["differences", "Differences"],
      ["cashMovement", "Cash Movement"],
      ["safeMovement", "Safe Movement"],
      ["balance", "Monthly Balance"],
      ["supplierJournal", "Supplier Journal"],
      ["supplier", "Supplier Statement"],
      ["partner", "Subcontractor Statement"],
      ["attendance", "Attendance"],
      ["salary", "Salary Report"],
      ["vehicle", "Service Vehicle"],
      ["cheque", "Cheque Statement"],
      ["encashment", "Encashment Statement"],
      ["employees", "Employees"],
      ["contracts", "Contracts"],
      ["leave", "Leave"],
    ];
    return `
      ${renderHeader(
        "Reports",
        "Report preview, print, official trace, and CSV export.",
        `<select class="report-select" data-report-select>${optionList(reportOptions, M.getActiveReport())}</select>
         <button class="icon-btn" type="button" title="Print" data-action="print">P</button>
         <button class="icon-btn secondary" type="button" title="Official PDF print" data-action="official-report">O</button>
         <button class="icon-btn primary" type="button" title="Export Excel CSV" data-action="export-csv">E</button>`
      )}
      ${renderReportSourceForm()}
      ${renderSection("Preview", renderEnhancedReportPreview())}
      ${renderSection(
        "Export History",
        renderTable(
          [
            { label: "Report", key: "reportName" },
            { label: "Period", key: "period" },
            { label: "Format", key: "format" },
            { label: "Generated By", key: "generatedBy" },
            { label: "Generated At", value: (row) => new Date(row.generatedAt).toLocaleString() },
          ],
          state.reportExports.slice(0, 20),
          { empty: "No export history yet." }
        )
      )}
    `;
  }

  function renderReportSourceForm() {
    if (M.getActiveReport() === "vehicle") {
      return renderForm(
        "Service Vehicle Entry",
        "vehicle",
        [
          { name: "date", label: "Date", type: "date", value: defaultDate(), required: true },
          { name: "amount", label: "Amount", type: "number", min: 0, step: "0.01", required: true },
          { name: "details", label: "Details", required: true },
          { name: "mileage", label: "Mileage", type: "number", min: 0 },
          { name: "gplExtraKm", label: "GPL / Extra KM", type: "number", min: 0, step: "0.01" },
          { name: "essenceExtraKm", label: "Essence / Extra KM", type: "number", min: 0, step: "0.01" },
        ],
        "Save vehicle",
        { periodScoped: true }
      );
    }
    if (M.getActiveReport() === "cheque") {
      return renderForm(
        "Cheque Entry",
        "cheque",
        [
          { name: "date", label: "Date", type: "date", value: defaultDate(), required: true },
          { name: "beneficiary", label: "Beneficiary", required: true },
          { name: "chequeNumber", label: "Cheque Number", required: true },
          { name: "amount", label: "Amount", type: "number", min: 0, step: "0.01", required: true },
          { name: "entries", label: "Entries", type: "number", min: 0, step: "0.01" },
          { name: "exits", label: "Exits", type: "number", min: 0, step: "0.01" },
          { name: "designation", label: "Designation", span: 2 },
        ],
        "Save cheque",
        { periodScoped: true }
      );
    }
    if (M.getActiveReport() === "encashment") {
      return renderForm(
        "Encashment Entry",
        "encashment",
        [
          { name: "date", label: "Date", type: "date", value: defaultDate(), required: true },
          { name: "designation", label: "Designation", value: "DIVERS CLIENTS", required: true },
          { name: "amount", label: "Amount", type: "number", min: 0, step: "0.01", required: true },
          { name: "observations", label: "Observations", type: "textarea", full: true },
        ],
        "Save encashment",
        { periodScoped: true }
      );
    }
    return "";
  }

  function reportDataset() {
    const t = totals();
    if (M.getActiveReport() === "supplier") {
      return {
        title: "Supplier Statement",
        columns: [
          { label: "Supplier", value: (row) => supplierName(row.supplierId) },
          { label: "Amount", key: "orderTotal", amount: true, format: money },
          { label: "Payment", key: "paidAmount", amount: true, format: money },
          { label: "Remaining", key: "remainingAmount", amount: true, format: money },
          { label: "Mode", key: "paymentMode" },
          { label: "Reference", key: "reference" },
          { label: "Status", key: "status" },
          { label: "Observation", key: "observation" },
        ],
        rows: scopedRows("supplierTransactions"),
        total: `Total remaining: ${money(t.supplierRemaining)}`,
      };
    }
    if (M.getActiveReport() === "supplierJournal") {
      return {
        title: "Supplier Journal",
        columns: [
          { label: "Date", key: "date" },
          { label: "Supplier", value: (row) => supplierName(row.supplierId) },
          { label: "Category", key: "category" },
          { label: "Order Total", key: "orderTotal", amount: true, format: money },
          { label: "Paid", key: "paidAmount", amount: true, format: money },
          { label: "Remaining", key: "remainingAmount", amount: true, format: money },
          { label: "Mode", key: "paymentMode" },
          { label: "Reference", key: "reference" },
          { label: "Status", key: "status" },
          { label: "Observation", key: "observation" },
        ],
        rows: scopedRows("supplierTransactions"),
        total: `Journal total: ${money(sum(scopedRows("supplierTransactions"), "orderTotal"))}`,
      };
    }
    if (M.getActiveReport() === "partner") {
      return {
        title: "Subcontractor and Convention Statement",
        columns: [
          { label: "Type", key: "type" },
          { label: "Name", key: "name" },
          { label: "Amount", key: "amount", amount: true, format: money },
          { label: "Payment", key: "payment", amount: true, format: money },
          { label: "Remaining", key: "remainingBalance", amount: true, format: money },
          { label: "Mode", key: "paymentMode" },
          { label: "Status", key: "status" },
          { label: "Date", key: "receptionDate" },
          { label: "Observation", key: "remarks" },
        ],
        rows: scopedRows("partners"),
        total: `Total remaining: ${money(sum(scopedRows("partners"), "remainingBalance"))}`,
      };
    }
    if (M.getActiveReport() === "cashExpenses") {
      return {
        title: "Cash Expenses",
        columns: [
          { label: "Date", key: "date" },
          { label: "Designation", key: "designation" },
          { label: "Amount", key: "amount", amount: true, format: money },
          { label: "Remark", key: "remark" },
        ],
        rows: scopedRows("cashExpenses"),
        total: `Total: ${money(sum(scopedRows("cashExpenses"), "amount"))}`,
      };
    }
    if (M.getActiveReport() === "differences") {
      return {
        title: "Differences",
        columns: [
          { label: "Date", key: "date" },
          { label: "User", key: "user" },
          { label: "Real Amount", key: "realAmount", amount: true, format: money },
          { label: "Virtual Amount", key: "virtualAmount", amount: true, format: money },
          { label: "Difference", key: "difference", amount: true, format: money },
          { label: "Remark", key: "remark" },
        ],
        rows: scopedRows("cashClosures"),
        total: `Net difference: ${money(sum(scopedRows("cashClosures"), "difference"))}`,
      };
    }
    if (M.getActiveReport() === "cashMovement") {
      return {
        title: "Cash Movement",
        columns: [
          { label: "Date", key: "date" },
          { label: "Cash CV", key: "cashCv", amount: true, format: money },
          { label: "Cash C", key: "cashC", amount: true, format: money },
          { label: "TPE", key: "tpe", amount: true, format: money },
          { label: "Total", key: "total", amount: true, format: money },
        ],
        rows: scopedRows("cashMovements"),
        total: `Total: ${money(sum(scopedRows("cashMovements"), "total"))}`,
        meta: cashMovementStats().map((row) => `${row.label}: avg ${money(row.average)} / min ${money(row.min)} / max ${money(row.max)}`),
      };
    }
    if (M.getActiveReport() === "safeMovement") {
      return {
        title: "Safe Movement",
        columns: [
          { label: "Date", key: "date" },
          { label: "Type", key: "type" },
          { label: "Designation", key: "designation" },
          { label: "Amount", key: "amount", amount: true, format: money },
          { label: "Category", key: "category" },
          { label: "Remark", key: "remark" },
        ],
        rows: [
          ...scopedRows("safeExits").map((row) => ({ ...row, type: "Safe Exit" })),
          ...scopedRows("profitabilityMovements").map((row) => ({ ...row, type: row.movementType, designation: row.detail, category: "Profitability", remark: row.destinationPeriod })),
        ],
        total: `Safe exits: ${money(sum(scopedRows("safeExits"), "amount"))}; profitability movement: ${money(sum(scopedRows("profitabilityMovements"), "amount"))}`,
      };
    }
    if (M.getActiveReport() === "balance") {
      return {
        title: "Monthly Balance",
        columns: [
          { label: "Indicator", key: "indicator" },
          { label: "Value", key: "value", amount: true, format: money },
        ],
        rows: [
          { indicator: "Revenue", value: t.globalRevenue },
          { indicator: "Expenses", value: t.expensesTotal },
          { indicator: "Profitability", value: t.profitability },
          { indicator: "Investments", value: t.investments },
          { indicator: "Net Profitability", value: t.netProfitability },
          { indicator: "Real Safe Net", value: t.realSafeNet },
        ],
        total: `Net profitability: ${money(t.netProfitability)}`,
      };
    }
    if (M.getActiveReport() === "attendance") {
      return {
        title: "Attendance",
        columns: [
          { label: "Date", key: "date" },
          { label: "Employee", value: (row) => employeeName(row.employeeId) },
          { label: "Code", key: "dayCode" },
          { label: "Note", key: "note" },
        ],
        rows: scopedRows("attendance"),
        total: `${scopedRows("attendance").length} attendance entries`,
      };
    }
    if (M.getActiveReport() === "salary") {
      return {
        title: "Salary Report",
        columns: [
          { label: "Employee", value: (row) => employeeName(row.employeeId) },
          { label: "Position", value: (row) => employeeFunction(row.employeeId) },
          { label: "Salary", key: "finalSalary", amount: true, format: money },
          { label: "Status", key: "status" },
          { label: "Remark", key: "remark" },
        ],
        rows: scopedRows("salaryReports"),
        total: `Total salaries: ${money(sum(scopedRows("salaryReports"), "finalSalary"))}`,
      };
    }
    if (M.getActiveReport() === "vehicle") {
      const vehicleRows = scopedRows("vehicleExpenses");
      const averageKm = vehicleRows.length ? sum(vehicleRows, "mileage") / vehicleRows.length : 0;
      return {
        title: "Service Vehicle Tracking",
        columns: [
          { label: "Date", key: "date" },
          { label: "Amount", key: "amount", amount: true, format: money },
          { label: "Details", key: "details" },
          { label: "Mileage", key: "mileage" },
          { label: "GPL / Extra KM", key: "gplExtraKm" },
          { label: "Essence / Extra KM", key: "essenceExtraKm" },
        ],
        rows: vehicleRows,
        total: `Total amount: ${money(sum(vehicleRows, "amount"))}`,
        meta: [
          `Total GPL: ${sum(vehicleRows, "gplExtraKm")}`,
          `Total Essence: ${sum(vehicleRows, "essenceExtraKm")}`,
          `Average KM/Fill: ${number(averageKm).toLocaleString("fr-DZ", { maximumFractionDigits: 2 })}`,
        ],
      };
    }
    if (M.getActiveReport() === "cheque") {
      const cheques = scopedRows("cheques");
      return {
        title: "Cheque Statement",
        columns: [
          { label: "Date", key: "date" },
          { label: "Beneficiary", key: "beneficiary" },
          { label: "Cheque", key: "chequeNumber" },
          { label: "Amount", key: "amount", amount: true, format: money },
          { label: "Entries", key: "entries", amount: true, format: money },
          { label: "Exits", key: "exits", amount: true, format: money },
          { label: "Running Balance", value: () => "Tracked" },
          { label: "Designation", key: "designation" },
        ],
        rows: cheques,
        total: `Total entries: ${money(sum(cheques, "entries"))}; total exits: ${money(sum(cheques, "exits"))}`,
        meta: [
          "Account amount on 31/12/previous year: prototype opening balance",
          "Running balance placeholder: final rule is still tracked and not fixed in this prototype.",
          `Year: ${state.selected.year}`,
        ],
      };
    }
    if (M.getActiveReport() === "employees") {
      return {
        title: "Employees",
        columns: [
          { label: "Full Name", key: "fullName" },
          { label: "Function", key: "function" },
          { label: "Birth Date", key: "birthDate" },
          { label: "Phone 01", key: "phone01" },
          { label: "Phone 02", key: "phone02" },
          { label: "Status", key: "status" },
        ],
        rows: state.employees,
        total: `${state.employees.length} employees`,
      };
    }
    if (M.getActiveReport() === "contracts") {
      return {
        title: "Contracts",
        columns: [
          { label: "Employee", value: (row) => employeeName(row.employeeId) },
          { label: "Hire Date", key: "hireDate" },
          { label: "CNAS", key: "cnasRegistrationDate" },
          { label: "Contract", key: "contractType" },
          { label: "From", key: "startsAt" },
          { label: "To", key: "endsAt" },
          { label: "Resignation", key: "resignationDate" },
          { label: "Status", key: "status" },
        ],
        rows: state.contracts,
        total: `${state.contracts.length} contracts`,
      };
    }
    if (M.getActiveReport() === "leave") {
      return {
        title: "Leave",
        columns: [
          { label: "Employee", value: (row) => employeeName(row.employeeId) },
          { label: "Year", key: "year" },
          { label: "Acquired", key: "acquiredDays" },
          { label: "Used", key: "usedDays" },
          { label: "Remaining", key: "remainingDays" },
          { label: "Remark", key: "remark" },
        ],
        rows: state.leaves.filter((row) => number(row.year) === state.selected.year),
        total: `Remaining leave: ${sum(state.leaves.filter((row) => number(row.year) === state.selected.year), "remainingDays")} days`,
      };
    }
    return {
      title: "Encashment Statement",
      columns: [
        { label: "Number", value: (_row, index) => index + 1 },
        { label: "Date", key: "date" },
        { label: "Designation", key: "designation" },
        { label: "Observations", key: "observations" },
        { label: "Amounts", key: "amount", amount: true, format: money },
      ],
      rows: scopedRows("encashments"),
      total: `Total: ${money(sum(scopedRows("encashments"), "amount"))}`,
      meta: [
        `ModernLam: ${labInfo.name}`,
        `NIF: ${labInfo.nif}`,
        `RIP: ${labInfo.rip}`,
        `Month/Year: ${monthNames[state.selected.month - 1]} ${state.selected.year}`,
      ],
    };
  }

  function reportPeriodLabel() {
    return `${monthNames[state.selected.month - 1]} ${state.selected.year}`;
  }

  function renderReportMetadata(dataset, printDate) {
    const rows = [
      { label: "Period", value: reportPeriodLabel() },
      { label: "Print Date", value: printDate },
      { label: "User", value: "Admin" },
      { label: "Rows", value: dataset.rows.length },
      { label: "Totals", value: dataset.total },
    ];
    return `
      <div class="report-meta-grid">
        ${rows.map((row) => `<div><span>${escapeHtml(row.label)}</span><strong>${escapeHtml(row.value)}</strong></div>`).join("")}
      </div>
    `;
  }

  function renderEnhancedReportPreview() {
    const dataset = reportDataset();
    const printDate = new Date().toLocaleString();
    const columns = dataset.columns.map((column) => ({
      ...column,
      value: column.value
        ? (row) => {
            const index = dataset.rows.indexOf(row);
            return column.value(row, index);
          }
        : column.value,
    }));
    return `
      <div class="report-preview">
        <div class="report-title">
          <div>
            <h2>${escapeHtml(dataset.title)}</h2>
            <span>${escapeHtml(labInfo.name)}</span><br>
            <span>NIF: ${escapeHtml(labInfo.nif)} | RIP: ${escapeHtml(labInfo.rip)}</span>
          </div>
          <div>
            <strong>${escapeHtml(reportPeriodLabel())}</strong><br>
            <span>Print date: ${escapeHtml(printDate)}</span><br>
            <span>User: Admin</span><br>
            <span>Draft / Official prototype preview</span>
          </div>
        </div>
        ${renderReportMetadata(dataset, printDate)}
        ${dataset.meta ? `<div class="alert-list">${dataset.meta.map((item) => `<div class="alert-item info"><span>${escapeHtml(item)}</span></div>`).join("")}</div>` : ""}
        ${renderTable(columns, dataset.rows, { empty: "No source data for this report." })}
        <div class="signature-row">
          <strong>${escapeHtml(dataset.total)}</strong>
          <div class="signature-box">Stamp</div>
          <div class="signature-box">Signature</div>
        </div>
      </div>
    `;
  }

  function renderReportPreview() {
    const dataset = reportDataset();
    const printDate = new Date().toLocaleString();
    const columns = dataset.columns.map((column) => ({
      ...column,
      value: column.value
        ? (row) => {
            const index = dataset.rows.indexOf(row);
            return column.value(row, index);
          }
        : column.value,
    }));
    return `
      <div class="report-preview">
        <div class="report-title">
          <div>
            <h2>${escapeHtml(dataset.title)}</h2>
            <span>${escapeHtml(labInfo.name)}</span><br>
            <span>NIF: ${escapeHtml(labInfo.nif)} · RIP: ${escapeHtml(labInfo.rip)}</span>
          </div>
          <div>
            <strong>${escapeHtml(monthNames[state.selected.month - 1])} ${state.selected.year}</strong><br>
            <span>Generated by Admin - ${escapeHtml(new Date().toLocaleDateString())}</span><br>
            <span>Draft / Official prototype preview</span>
          </div>
        </div>
        ${dataset.meta ? `<div class="alert-list">${dataset.meta.map((item) => `<div class="alert-item ok"><span>${escapeHtml(item)}</span></div>`).join("")}</div>` : ""}
        ${renderTable(columns, dataset.rows, { empty: "No source data for this report." })}
        <div class="signature-row">
          <strong>${escapeHtml(dataset.total)}</strong>
          <div class="signature-box">Stamp</div>
          <div class="signature-box">Signature</div>
        </div>
      </div>
    `;
  }

  M.setReportDatasetProvider(reportDataset);
  M.registerView('reports', renderReports);
})();
